project:
  type: book

book:
  title: "Prompt Engineering Notes"
  author: "Kittipos Sirivongrungson"
  date: "9/9/2024"
  repo-url: https://github.com/Lightbridge-KS/prompt-engineer-notes
  site-url: https://prompt-engineer-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: Real World (Anthropic)
      chapters: 
        - "real-world/01_prompting_recap.ipynb"
        - "real-world/02_medical_prompt.ipynb"
        - "real-world/03_prompt_engineering.ipynb"



bibliography: references.bib

format:
  html:
    theme: cosmo
    toc-depth: 4

execute: 
  freeze: auto


